## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df= application_df.drop(columns= ['EIN','NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
count_apps= application_df['APPLICATION_TYPE'].value_counts()
count_apps

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace= list(count_apps[count_apps<500].index)
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classification= application_df['CLASSIFICATION'].value_counts()

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification[classification > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace= list(classification[classification < 1000].index)
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df= pd.get_dummies(application_df)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
y= application_df["IS_SUCCESSFUL"]
X= application_df.drop(columns="IS_SUCCESSFUL").values

print(y.value_counts(normalize=True))

1    0.532406
0    0.467594
Name: IS_SUCCESSFUL, dtype: float64

In [11]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer. (test 2)
#  YOUR CODE GOES HERE

input_dimen= len(X_train_scaled[0])
nn_2 = tf.keras.models.Sequential()

# First hidden layer
nn_2.add(tf.keras.layers.Dense(units= 50,activation='tanh',input_dim= input_dimen))

# Second hidden layer
nn_2.add(tf.keras.layers.Dense(units= 25,activation='tanh'))
# Third hidden layer
nn_2.add(tf.keras.layers.Dense(units= 25,activation='tanh'))
# Fourth hidden layer
nn_2.add(tf.keras.layers.Dense(units= 25,activation='tanh'))
# Fifth hidden layer
nn_2.add(tf.keras.layers.Dense(units= 25,activation='tanh'))
# Sixth hidden layer
nn_2.add(tf.keras.layers.Dense(units= 50,activation='tanh'))
# Output layer
nn_2.add(tf.keras.layers.Dense(units= 1,activation='sigmoid'))

# Check the structure of the model
nn_2.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 50)                2200

 dense_1 (Dense)             (None, 25)                1275

 dense_2 (Dense)             (None, 25)                650

 dense_3 (Dense)             (None, 25)                650

 dense_4 (Dense)             (None, 25)                650

 dense_5 (Dense)             (None, 50)                1300

 dense_6 (Dense)             (None, 1)                 51

=================================================================
Total params: 6,776
Trainable params: 6,776
Non-trainable params: 0
_________________________________________________________________

In [14]:
# Compile the model
nn_2.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

In [15]:
# Train the model 2
fit_model= nn_2.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 7s 4ms/step - loss: 0.5725 - accuracy: 0.7228
Epoch 2/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5595 - accuracy: 0.7268
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5549 - accuracy: 0.7296
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5527 - accuracy: 0.7308
Epoch 5/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5518 - accuracy: 0.7301
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5502 - accuracy: 0.7304
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5490 - accuracy: 0.7332
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7310
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5471 - accuracy: 0.7339
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5476 - accuracy: 0.7299
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7326
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7340
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5454 - accuracy: 0.7340
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7342
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7341
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5434 - accuracy: 0.7355
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7348
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7346
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.7355
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7361
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7368
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7355
Epoch 23/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7363
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7359
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5400 - accuracy: 0.7371
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5401 - accuracy: 0.7365
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7376
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5395 - accuracy: 0.7381
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5389 - accuracy: 0.7379
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5389 - accuracy: 0.7371
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7379
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7367
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7380
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7390
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7371
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5371 - accuracy: 0.7379
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7378
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5369 - accuracy: 0.7386
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5367 - accuracy: 0.7393
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5366 - accuracy: 0.7380
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5368 - accuracy: 0.7386
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7382
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5365 - accuracy: 0.7379
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7389
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7404
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7397
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5364 - accuracy: 0.7385
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5352 - accuracy: 0.7384
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5355 - accuracy: 0.7395
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7395
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7391
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5353 - accuracy: 0.7401
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5350 - accuracy: 0.7394
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5353 - accuracy: 0.7398
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5348 - accuracy: 0.7390
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5344 - accuracy: 0.7407
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5346 - accuracy: 0.7398
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5353 - accuracy: 0.7395
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5345 - accuracy: 0.7400
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7392
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7399
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5342 - accuracy: 0.7398
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5343 - accuracy: 0.7404
Epoch 64/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5337 - accuracy: 0.7392
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5340 - accuracy: 0.7402
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5340 - accuracy: 0.7404
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5345 - accuracy: 0.7393
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5335 - accuracy: 0.7403
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5336 - accuracy: 0.7403
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7407
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7392
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5336 - accuracy: 0.7397
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5336 - accuracy: 0.7398
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5333 - accuracy: 0.7393
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5335 - accuracy: 0.7401
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5339 - accuracy: 0.7400
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7403
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5335 - accuracy: 0.7394
Epoch 79/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7406
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7410
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7397
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7395
Epoch 83/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5336 - accuracy: 0.7402
Epoch 84/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5337 - accuracy: 0.7405
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5332 - accuracy: 0.7406
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5337 - accuracy: 0.7401
Epoch 87/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5329 - accuracy: 0.7409
Epoch 88/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5331 - accuracy: 0.7407
Epoch 89/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7400
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7405
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7414
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5327 - accuracy: 0.7400
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5332 - accuracy: 0.7408
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7398
Epoch 95/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5331 - accuracy: 0.7409
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5327 - accuracy: 0.7413
Epoch 97/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7411
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5325 - accuracy: 0.7407
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7407
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7407

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_2.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5609 - accuracy: 0.7270 - 386ms/epoch - 1ms/step
Loss: 0.5609061121940613, Accuracy: 0.7269970774650574

In [17]:
# Define the model 3 - deep neural net, i.e., the number of input features and hidden nodes for each layer. (test 2)


input_dimen= len(X_train_scaled[0])
nn_3 = tf.keras.models.Sequential()

# First hidden layer
nn_3.add(tf.keras.layers.Dense(units= 250,activation='relu',input_dim= input_dimen))

# Second hidden layer
nn_3.add(tf.keras.layers.Dense(units= 250,activation='leaky_relu'))
# Third hidden layer
nn_3.add(tf.keras.layers.Dense(units= 250,activation='leaky_relu'))
# Fourth hidden layer
nn_3.add(tf.keras.layers.Dense(units= 250,activation='leaky_relu'))
# Fifth hidden layer
nn_3.add(tf.keras.layers.Dense(units= 250,activation='leaky_relu'))
# Sixth hidden layer
nn_3.add(tf.keras.layers.Dense(units= 250,activation='leaky_relu'))
# Seventh hidden layer
nn_3.add(tf.keras.layers.Dense(units= 250,activation='leaky_relu'))
# Eight hidden layer
nn_3.add(tf.keras.layers.Dense(units= 250,activation='leaky_relu'))
# Ninth hidden layer
nn_3.add(tf.keras.layers.Dense(units= 250,activation='relu'))

# Output layer
nn_3.add(tf.keras.layers.Dense(units= 1,activation='sigmoid'))

# Check the structure of the model
nn_3.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_7 (Dense)             (None, 250)               11000

 dense_8 (Dense)             (None, 250)               62750

 dense_9 (Dense)             (None, 250)               62750

 dense_10 (Dense)            (None, 250)               62750

 dense_11 (Dense)            (None, 250)               62750

 dense_12 (Dense)            (None, 250)               62750

 dense_13 (Dense)            (None, 250)               62750

 dense_14 (Dense)            (None, 250)               62750

 dense_15 (Dense)            (None, 250)               62750

 dense_16 (Dense)            (None, 1)                 251

=================================================================
Total params: 513,251
Trainable params: 513,251
Non-trainable params: 0
_________________________________________________________________

In [18]:
# Compile the model
nn_3.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

In [19]:
# Train the model 3
fit_model_3= nn_3.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 9s 9ms/step - loss: 0.5766 - accuracy: 0.7206
Epoch 2/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5634 - accuracy: 0.7252
Epoch 3/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5602 - accuracy: 0.7270
Epoch 4/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5562 - accuracy: 0.7284
Epoch 5/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5562 - accuracy: 0.7275
Epoch 6/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5530 - accuracy: 0.7299
Epoch 7/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5506 - accuracy: 0.7299
Epoch 8/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5518 - accuracy: 0.7306
Epoch 9/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5517 - accuracy: 0.7310
Epoch 10/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5512 - accuracy: 0.7330
Epoch 11/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5486 - accuracy: 0.7332
Epoch 12/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5486 - accuracy: 0.7331
Epoch 13/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5483 - accuracy: 0.7328
Epoch 14/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5511 - accuracy: 0.7333
Epoch 15/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5534 - accuracy: 0.7318
Epoch 16/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5481 - accuracy: 0.7326
Epoch 17/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5460 - accuracy: 0.7348
Epoch 18/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5462 - accuracy: 0.7344
Epoch 19/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5466 - accuracy: 0.7345
Epoch 20/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5467 - accuracy: 0.7344
Epoch 21/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5459 - accuracy: 0.7356
Epoch 22/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5455 - accuracy: 0.7353
Epoch 23/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5460 - accuracy: 0.7352
Epoch 24/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5452 - accuracy: 0.7348
Epoch 25/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5448 - accuracy: 0.7354
Epoch 26/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5442 - accuracy: 0.7344
Epoch 27/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5443 - accuracy: 0.7348
Epoch 28/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5441 - accuracy: 0.7350
Epoch 29/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5441 - accuracy: 0.7359
Epoch 30/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5424 - accuracy: 0.7367
Epoch 31/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5435 - accuracy: 0.7363
Epoch 32/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5439 - accuracy: 0.7361
Epoch 33/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5422 - accuracy: 0.7355
Epoch 34/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5438 - accuracy: 0.7357
Epoch 35/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5441 - accuracy: 0.7340
Epoch 36/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5419 - accuracy: 0.7364
Epoch 37/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5409 - accuracy: 0.7388
Epoch 38/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5474 - accuracy: 0.7350
Epoch 39/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5417 - accuracy: 0.7371
Epoch 40/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5411 - accuracy: 0.7378
Epoch 41/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5410 - accuracy: 0.7376
Epoch 42/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5416 - accuracy: 0.7369
Epoch 43/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5417 - accuracy: 0.7370
Epoch 44/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5503 - accuracy: 0.7346
Epoch 45/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5439 - accuracy: 0.7366
Epoch 46/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5410 - accuracy: 0.7383
Epoch 47/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5412 - accuracy: 0.7372
Epoch 48/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5448 - accuracy: 0.7374
Epoch 49/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5405 - accuracy: 0.7377
Epoch 50/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5427 - accuracy: 0.7341
Epoch 51/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5513 - accuracy: 0.7311
Epoch 52/100
804/804 [==============================] - 7s 9ms/step - loss: 0.6217 - accuracy: 0.6923
Epoch 53/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5786 - accuracy: 0.7353
Epoch 54/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5692 - accuracy: 0.7322
Epoch 55/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5600 - accuracy: 0.7352
Epoch 56/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5577 - accuracy: 0.7348
Epoch 57/100
804/804 [==============================] - 8s 9ms/step - loss: 0.5565 - accuracy: 0.7336
Epoch 58/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5562 - accuracy: 0.7342
Epoch 59/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5582 - accuracy: 0.7329
Epoch 60/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5532 - accuracy: 0.7347
Epoch 61/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5515 - accuracy: 0.7344
Epoch 62/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5872 - accuracy: 0.7234
Epoch 63/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5617 - accuracy: 0.7311
Epoch 64/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5555 - accuracy: 0.7334
Epoch 65/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5552 - accuracy: 0.7323
Epoch 66/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5555 - accuracy: 0.7341
Epoch 67/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5559 - accuracy: 0.7331
Epoch 68/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5538 - accuracy: 0.7334
Epoch 69/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5533 - accuracy: 0.7326
Epoch 70/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5541 - accuracy: 0.7343
Epoch 71/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5518 - accuracy: 0.7360
Epoch 72/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5517 - accuracy: 0.7353
Epoch 73/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5552 - accuracy: 0.7337
Epoch 74/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5599 - accuracy: 0.7300
Epoch 75/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5537 - accuracy: 0.7345
Epoch 76/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5522 - accuracy: 0.7353
Epoch 77/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5521 - accuracy: 0.7345
Epoch 78/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5504 - accuracy: 0.7351
Epoch 79/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5515 - accuracy: 0.7354
Epoch 80/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5802 - accuracy: 0.7320
Epoch 81/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5556 - accuracy: 0.7341
Epoch 82/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5531 - accuracy: 0.7353
Epoch 83/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5506 - accuracy: 0.7355
Epoch 84/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5502 - accuracy: 0.7365
Epoch 85/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5583 - accuracy: 0.7344
Epoch 86/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5684 - accuracy: 0.7282
Epoch 87/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5575 - accuracy: 0.7322
Epoch 88/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5527 - accuracy: 0.7346
Epoch 89/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5512 - accuracy: 0.7366
Epoch 90/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5513 - accuracy: 0.7346
Epoch 91/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5523 - accuracy: 0.7360
Epoch 92/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5722 - accuracy: 0.7331
Epoch 93/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5574 - accuracy: 0.7332
Epoch 94/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5571 - accuracy: 0.7322
Epoch 95/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5586 - accuracy: 0.7299
Epoch 96/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5685 - accuracy: 0.7313
Epoch 97/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5560 - accuracy: 0.7337
Epoch 98/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5549 - accuracy: 0.7325
Epoch 99/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5680 - accuracy: 0.7316
Epoch 100/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5836 - accuracy: 0.7276

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_3.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5720 - accuracy: 0.7237 - 573ms/epoch - 2ms/step
Loss: 0.5720235705375671, Accuracy: 0.7237317562103271

In [21]:
# Export our model to HDF5 file
file_name = "AlphabetSoupCharity-Optimization-Manual.h5"
nn_3.save(file_name)

In [22]:
# Downloading files to local doc
from google.colab import files
files.download(file_name)